TermPaper : TermPaperCBR.class
	java -cp .:../lib/\* TermPaperCBR data/term_paper_data.csv term_paper.fcl
	
TermPaperCBR.class : TermPaperCBR.java
	javac -cp ../lib/\* TermPaperCBR.java

clean :
	rm *.class
