Attrition : AttritionCBR.class
	java -cp .:../lib/\* AttritionCBR data/train.csv data/test.csv attrition.fcl
	
AttritionCBR.class : AttritionCBR.java
	javac -cp ../lib/\* AttritionCBR.java
	
clean :
	rm *.class
